import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import App from "@/pages/_app";
import Main from "@/components/Main";
import About from "@/components/about";
import Particle from "@/components/Particle";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ayush||Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Particle />
      <Navbar />
      <Main />
      <About />
    </div>
  );
}
